// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-jAMqynLl0lUmV0cx0In5bG4TSMK5Lc',
    appId: '1:236422576815:web:946af18c818798092bb25a',
    messagingSenderId: '236422576815',
    projectId: 'vuka265-6z79ng',
    authDomain: 'vuka265-6z79ng.firebaseapp.com',
    storageBucket: 'vuka265-6z79ng.firebasestorage.app',
    measurementId: 'G-WDS37X213T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBybwa8K1680fw6Op_ThpahD-LikYCG8f0',
    appId: '1:236422576815:android:4c31d92cf0de37a32bb25a',
    messagingSenderId: '236422576815',
    projectId: 'vuka265-6z79ng',
    storageBucket: 'vuka265-6z79ng.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNA5Wde48so21sAs3hPe9FRIVcgwZ330o',
    appId: '1:236422576815:ios:70da1995ef2c79db2bb25a',
    messagingSenderId: '236422576815',
    projectId: 'vuka265-6z79ng',
    storageBucket: 'vuka265-6z79ng.firebasestorage.app',
    androidClientId: '236422576815-9fn37evnjuqs4vmjfku0grmmbt38s5sg.apps.googleusercontent.com',
    iosClientId: '236422576815-6gej3g18ut7seu4qmvm1o6gsco0pf22l.apps.googleusercontent.com',
    iosBundleId: 'com.vukaapp.vukaglobal',
  );

}